//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcc2
    {
        public int id { get; set; }
        public string productn { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> fstid { get; set; }
    
        public virtual mvcc1 mvcc1 { get; set; }
    }
}
