//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcc1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcc1()
        {
            this.mvcc2 = new HashSet<mvcc2>();
        }
    
        public int id { get; set; }
        public string cosname { get; set; }
        public string mobileno { get; set; }
        public string address { get; set; }
        public Nullable<int> total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcc2> mvcc2 { get; set; }
    }
}
